### ISSUE TITLE
query regarding render with big view change

### ISSUE THREAD

**Issue by Torment123** [donydchen/mvsplat#10]
Hi, thanks for the great work. I have some question about the advantages and limitations of feature matching cost volume formulation:

1. I see in the paper that the rendered novel views have large view overlap w.r.t. the input views, this makes sense because the feature matching clue between input views can only help determining the depth of those pixel in the input views, but not the occluded side of the view (e.g., the back side of a car)
2. If my observation is reasonable, does it mean that if I want to learn novel view synthesis where the novel view is significanly different than the input view (like shifting to the occluded side of input view), the feature matching volume alone won't help much? 

Thanks

**Comment by donydchen** [comment]
Hi @Torment123, thanks for your interest in our work.

The 'overlap' is our paper is more related to 'the overlap between _input views_'. Since the cost volume is built by warping one input view to another selected input view, it does assume that there is enough overlap between these two input views, otherwise, it cannot infer meaningful matching information.

If I understand correctly, the case you mentioned is more about the overlap between _the input view and the target view_. In such an occlusion case, it basically means that the model should have some capabilities to 'hallucinate' / 'guess' the occluded region, which is not the aim of the cost volume. And I agree that feature matching volume alone won't help much here.

**Comment by Torment123** [comment]
> Hi @Torment123, thanks for your interest in our work.
> 
> The 'overlap' is our paper is more related to 'the overlap between _input views_'. Since the cost volume is built by warping one input view to another selected input view, it does assume that there is enough overlap between these two input views, otherwise, it cannot infer meaningful matching information.
> 
> If I understand correctly, the case you mentioned is more about the overlap between _the input view and the target view_. In such an occlusion case, it basically means that the model should have some capabilities to 'hallucinate' / 'guess' the occluded region, which is not the aim of the cost volume. And I agree that feature matching volume alone won't help much here.

Thanks for the fast reply, yes I did mean the overlap between input and target view. Your explanation helps a lot.
