### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by Yuxiiin** [donydchen/mvsplat#22]
Thank you for your excellent work！

I noted that your evaluation mainly focus on rendering speed，then how many hours does it take to train the model？

**Comment by donydchen** [comment]
Hi @Yuxiiin, thanks for your interest in our work.

With the default settings, the training time of MVSplat is around **5.5 days** on a single A100. However, the training speed can be significantly boosted with multiple GPUs as long as the overall batch size remains the same. For example, if you use 7 GPUs, each with batch_size=2, the final performance will be similar, but the training time will be significantly shorter. That is also the main reason we mainly evaluate the inference speed since, for inference, typically, the settings reported by different papers/models are the same, e.g., all use batch_size=1, tested on a single GPU, etc.
