### ISSUE TITLE
About the prediction of opacity.

### ISSUE THREAD

**Issue by Mayzazhou** [donydchen/mvsplat#29]
As in the paper, Sect. 3.2, the opacity is predicted from the matching confidence with 2 convolution layers. However, I can only find the function `map_pdf_to_opacity` in the code that maps densities to opacities. 

I wonder which one is the final implementation. Looking forward to your reply!

**Comment by donydchen** [comment]
Hi @Mayzazhou, thanks for your interest in our work.

We use two convolution layers to predict the density, see [here](https://github.com/donydchen/mvsplat/blob/main/src/model/encoder/costvolume/depth_predictor_multiview.py#L254-L260), which is then mapped to opacity via the [map_pdf_to_opacity](https://github.com/donydchen/mvsplat/blob/main/src/model/encoder/encoder_costvolume.py#L127-L140) function. Since the mapping is a deterministic operation (not something learnable), we mix the use of density and opacity in the writing for simplicity.

**Comment by Mayzazhou** [comment]
Thanks a lot for your response. My problem is solved! :-)
