### ISSUE TITLE
Custom Dataset + Exporting to PLY

### ISSUE THREAD

**Issue by yousefh409** [donydchen/mvsplat#5]
Hi,
I was wondering if there were any resources for training on custom data (video/images + COLMAP camera poses)?
Also, is there a way for exporting the model to a renderable PLY format?

**Comment by donydchen** [comment]
Hi @yousefh409, you can refer to https://github.com/donydchen/mvsplat/issues/1 for more information about how to train and test on customised datasets.

---

A reference on how to export to PLY file is provided at https://github.com/donydchen/mvsplat/blob/main/src/paper/generate_point_cloud_figure_mvsplat.py. You can run it via:

```bash
python -m src.paper.generate_point_cloud_figure_mvsplat \
+experiment=re10k \
checkpointing.load=checkpoints/re10k.ckpt \
mode=test \
dataset/view_sampler=evaluation
```

Keep in mind that the above is a one-off script and might require some modifications to make it runnable. Additionally, since MVSplat uses pixelSplat as its codebase, you can also refer to some additional information that pixelSplat has provided at https://github.com/dcharatan/pixelsplat/issues/9.
