### ISSUE TITLE
Inference on image regions without overlap

### ISSUE THREAD

**Issue by penguinflys** [donydchen/mvsplat#63]
Hello, thanks for the excellent contribution and very well-organized code.

I understand that MVS often has difficulty estimating depth in regions without overlap in the source image. However, your paper demonstrates impressive depth accuracy for the lamp, which appears to be a region with limited overlap. Could you elaborate on the techniques or modifications you employed to achieve this result?

![image](https://github.com/user-attachments/assets/ddc8767d-2d95-41d4-8b19-a322f412d5e6)

**Comment by penguinflys** [comment]
@donydchen Can you please offer any explains, although my question might be stupid?

**Comment by xiaoc57** [comment]
@penguinflys Hello. Although I am not the author of this project, I have been studying related problems recently. I think that recovering scenes from non-overlapping views is because the model learns the depth from the features. Because the model not only recovers the depth from the cost volume, but also predicts the depth from the original features.

**Comment by penguinflys** [comment]
@xiaoc57 Yes, You are right. I didn't see the skip connection.
![image](https://github.com/user-attachments/assets/447fc5e9-2a3b-44d2-a354-f05cd32f88a1)
